version : "3"
services:
        zookeeper:
                image: aawaali/alpine-zookeeper
                container_name: zookeeper
                ports:
                        - 2181:2181
        kafka:
                image: aawaali/alpine-kafka
                container_name: kafka
                hostname: kafka
                ports:
                        - 9092:9092
                depends_on:
                        - zookeeper

